name: Pull Request Merged

on:
    pull_request:
        branches: [main]
        types:
            - closed

jobs:
    on_merge:
        name: On Merge
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Update Asana task
              uses: de-id/update-asana-tasks@main
              with:
                  asana-pat: ${{ secrets.ASANA_PAT }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
