name: Test SDK with Local Development

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: 'SDK version to test (e.g., 1.1.0-beta.6)'
        required: true
        type: string
      environment:
        description: 'Environment to test against'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  test-sdk-locally:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout agents-ui repository
        uses: actions/checkout@v4
        with:
          repository: de-id/agents-ui
          ref: 'staging'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install specific SDK version
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "Testing with staging SDK version: ${{ github.event.inputs.sdk_version }}"
            yarn add @d-id/client-sdk@npm:@d-id/client-sdk-staging@${{ github.event.inputs.sdk_version }}
          else
            echo "Testing with production SDK version: ${{ github.event.inputs.sdk_version }}"
            yarn add @d-id/client-sdk@${{ github.event.inputs.sdk_version }}
          fi

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run E2E tests against specific environment
        env:
          NODE_ENV: ${{ github.event.inputs.environment }}
          E2E_USER_APIKEY: ${{ secrets.E2E_USER_APIKEY_STAGING }}
          VITE_CLIENT_KEY: ${{ secrets.VITE_CLIENT_KEY_STAGING }}
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            yarn test:staging
          else
            yarn test:prod
          fi

      - name: Report results
        if: always()
        run: |
          echo "✅ SDK version ${{ github.event.inputs.sdk_version }} tested against ${{ github.event.inputs.environment }} environment"
          echo "Environment separation validation completed"
